article/urls.py
from django.conf.urls import patterns, url

# Uncomment the next two lines to enable the admin:
from article import views

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'newsdemo.views.home', name='home'),
    # url(r'^newsdemo/', include('newsdemo.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
	url(r'^report/$', views.news_report, name='report'),
	url(r'^article/$', views.news_article, name='article'),
	url(r'^show/(\d+)/$', views.news_aid, name='show'),
)

composeexample/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from composeexample import views
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^article/', include('article.urls', namespace="article")),
    url(r'^admin/', include(admin.site.urls)),
]

polls/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView, ListView
from polls import views
from polls.models import Poll

urlpatterns = patterns('',
    url(r'^$', 
	ListView.as_view(
		queryset=Poll.objects.order_by('-pub_date')[:5],
		context_object_name='latest_poll_list',
		template_name='polls/index.html'), 
	name='index'),
    # ex: /polls/5/
    url(r'^(?P<pk>\d+)/$', 
	DetailView.as_view(
            model=Poll,
            template_name='polls/detail.html'),
	name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<pk>\d+)/results/$', 
	DetailView.as_view(
            model=Poll,
            template_name='polls/results.html'),
	name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

article/models.py
from django.db import models
from django.contrib import admin 

# Create your models here.
class List(models.Model): 
 title = models.CharField(max_length=250, unique=True) 
 def __unicode__(self): 
   return self.title 
 class Meta: 
   ordering = ['title'] 
 class Admin: 
   pass
   
import datetime 

class Item(models.Model): 
 title = models.CharField(max_length=250) 
 content = models.CharField(max_length=10240)
 created_date = models.DateTimeField(default=datetime.datetime.now) 
 completed = models.BooleanField(default=False) 
 article_list = models.ForeignKey(List) 
 def __unicode__(self): 
   return self.title 
 class Meta: 
   ordering = ['-created_date', 'title'] 
 class Admin: 
   pass
   
admin.site.register(List)
admin.site.register(Item)

polls/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __unicode__(self):
        return self.question
    def was_published_recently(self):
	now = timezone.now()
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1) > now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __unicode__(self):
        return self.choice_text

article/views.py
# Create your views here.
from django.shortcuts import render_to_response
from article.models import List
from article.models import Item 

def news_report(request):
 article_listing = []
 for article_list in List.objects.all():
   article_dict = {}
   article_dict['news_object'] = article_list
   article_dict['item_count'] = article_list.item_set.count()
   article_dict['items_title'] = article_list.title
   article_listing.append(article_dict)
 return render_to_response('show_report.html', { 'article_listing': article_listing })


def news_article(request):
 article_listing = []
 for article_list in Item.objects.all():
   article_dict = {}
   article_dict['news_object'] = article_list
   article_dict['article_list'] = article_list.article_list
   article_dict['items_id'] = article_list.id
   article_dict['items_title'] = article_list.title
   article_dict['items_content'] = article_list.content
   article_dict['created_date'] = article_list.created_date
   article_listing.append(article_dict)
 return render_to_response('show_list.html', { 'article_listing': article_listing })

def news_aid(request, aid):
 article_listing = {}
 article = Item.objects.get( id = aid )
 if article:
  article_listing['items_title'] = article.title
  article_listing['items_content'] = article.content
  article_listing['created_date'] = article.created_date
 return render_to_response('show_article.html', { 'article_listing': article_listing })

composeexample/views.py
# Create your views here.
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from polls.models import Poll

def home(request):
    return render(request,"home.html",{})
        # return HttpResponseRedirect(reverse('polls:index'))

polls/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.template import Context, loader
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from polls.models import Poll, Choice
from django.http import Http404

def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'polls/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

article/templates/show_article.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
 <head> 
   <meta http-equiv="Content-Type" content="text/html" /> 
   <title>{{ article_listing.items_title }}</title> 
 </head> 
 <body> 
    <div align="center"><h1>{{ article_listing.items_title }}</h1> 
    <h3>发表时间: {{ article_listing.created_date }}</h3></div>
   <ul> 
	 新闻内容: {{ article_listing.items_content }}
   </ul> 
 </body> 
</html>

article/templates/show_list.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
   <meta http-equiv="Content-Type" content="text/html" />
   <title>新闻中心</title>
 </head>
 <body>
   <h1>新闻中心</h1>
{% for list_dict in article_listing %}
   <h2>{{ list_dict.list_object.title }}</h2>
   <ul>
   	 <li>新闻分类: {{ list_dict.article_list }}</li>
     <li>新闻标题: <a href="{% url 'article:show' list_dict.items_id %}">{{ list_dict.items_title }}</a></li> 
	 <li>发表时间: {{ list_dict.created_date }}</li>
   </ul>
{% endfor %}
 </body>
</html>

article/templates/show_report.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
 <head> 
   <meta http-equiv="Content-Type" content="text/html" /> 
   <title>新闻统计</title> 
 </head> 
 <body> 
   <h1>新闻统计中心</h1> 
{% for list_dict in article_listing %} 
   <ul> 
   	 <li>新闻标题: {{ list_dict.items_title }}</li> 
     <li>新闻数目: {{ list_dict.item_count }}</li> 
   </ul> 
{% endfor %} 
 </body> 
</html>

composeexample/templates/home.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
   <meta http-equiv="Content-Type" content="text/html" />
   <title>首页</title>
 </head>
 <body>
     <a href="{% url 'article:article' %}">文章</a>
     <br>
     <a href="{% url 'polls:index' %}">投票</a>
 </body>
</html>

polls/templates/polls/detail.html
<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' poll.id %}" method="post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% if latest_poll_list %}
    <ul>
    {% for poll in latest_poll_list %}
        <li><a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>